import Head from "next/head";
import Login from "../components/Login";
export default function Home() {
  return (
    <div className="bg-fixed bg-no-repeat bg-cover bg-center bg-[url('../public/bg1.svg')]">
      <Head>
        <title>Hari Charan K | Front-end Developer and Artist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
}
