import Head from "next/head";
import Login from "../components/Login";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../utils/firebase";
import { useRouter } from "next/router";
import { DominoSpinner } from "react-spinners-kit";

export default function Home() {
  const [user, loading] = useAuthState(auth);
  const router = useRouter();
  if (loading)
    return (
      <div className="flex justify-center mt-[35vh]">
        <DominoSpinner size={400} color="#000000" />;
      </div>
    );
  if (user) router.push("/user");
  return (
    <div className="bg-fixed bg-no-repeat bg-cover bg-center bg-[url('../public/bg1.svg')]">
      <Head>
        <title>DDMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
}
